# Config file for VoxelMorph
model_cfg = dict(
    type='VXM',
    encoder_cfg=dict(
        spatial_dims=3,
        in_chan=2,
        down=True,
        out_channels=[16, 32, 64, 96, 128],
        out_indices=[1, 2, 3, 4],
        block_config=dict(
            kernel_size=3,
            res_skip=False,
            down_first=True,
            conv_down=True,
            bias=True,
            pool_name=None, # if conv_down==False: ('max', {'kernel_size': 2}),
            norm_name=('INSTANCE', {'affine': False}),
            act_name=("leakyrelu", {"inplace": True, "negative_slope": 0.2}),
            dropout=None,
        ),
    ),
    decoder_cfg=dict(
        spatial_dims=3,
        skip_channels=[128, 96, 64, 32],
        out_channels=[128, 96, 64, 32],
        block_config=dict(
            kernel_size=3,
            res_skip=False,
            up_transp_conv=True,
            transp_bias=False,
            upsample_kernel_size=2,
            bias=True,
            norm_name=('INSTANCE', {'affine': False}),
            act_name=("leakyrelu", {"inplace": True, "negative_slope": 0.2}),
            dropout=None,
        ),
    ),
    remain_cfg=dict(
        spatial_dims=3,
        in_chan=32,
        down=False,
        out_channels=[32] * 2,
        out_indices=[1],
        block_config=dict(
            kernel_size=3,
            res_skip=False,
            bias=True,
            norm_name=('INSTANCE', {'affine': False}),
            act_name=("leakyrelu", {"inplace": True, "negative_slope": 0.2}),
            dropout=None,
        ),
    ),
)